name: Check Docker Tags

on:
  push:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Docker tags
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ublue-os/bluefin-dx-nvidia

      - name: Print tags
        run: |
          echo "${{ steps.docker_metadata.outputs.tags }}"

  scan:
    name: List Recent Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Docker Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
          image: ghcr.io/ublue-os/bluefin-dx-nvidia
          max-age-minutes: 1440
        id: scan
      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.tags }}'"
