name: Check Docker Tags

on:
  push:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday

jobs:
  list-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: List Docker Image Tags
      run: |
        IMAGE_NAME="ghcr.io/ublue-os/bluefin-dx-nvidia"
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${IMAGE_NAME}/tags/list"
